export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const ADD_REMOVE_WISHLIST_COMPARE_SUCCESS = 'ADD_REMOVE_WISHLIST_COMPARE_SUCCESS';
export const LOAD_AIRCRAFTS_SUCCESS = 'LOAD_AIRCRAFTS_SUCCESS';